on: push
name: Build, Test, and Publish if master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      uses: mikeal/npx@master
      with:
        entrypoint: npm
        args: install
    - name: Test
      uses: mikeal/npx@master
      with:
        entrypoint: npm
        args: test
    - name: Publish
      if: github.ref == 'refs/heads/master' 
      uses: mikeal/merge-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
